import { Navbar } from "@/components/layout/NavBar";
import React from "react";

export default function TermsOfUsePage() {
  return (
    <main className="min-h-screen selection:bg-white selection:text-black">
      <Navbar />
      <div className="max-w-3xl mx-auto font-sans pt-20 pb-24 px-6 md:px-8">
        {/* Header Section */}
        <h1 className="text-4xl md:text-[44px] tracking-tight text-white mb-2 font-medium">
          Terms of Use
        </h1>
        <p className="text-white/50 text-sm md:text-base mb-10">
          Last updated: 25 March, 2026
        </p>

        {/* Content Section */}
        <div className="space-y-10 text-white/70 text-base leading-relaxed">
          <p>
            Welcome to LayerTao. By accessing or using our platform, APIs, or
            services (“Services”), you agree to these Terms of Use.
          </p>

          {/* 1. Overview */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              1. Overview
            </h2>
            <p>
              LayerTao provides a middleware layer that enables developers to
              interact with decentralized AI networks, including but not limited
              to Bittensor subnets, through a unified interface.
            </p>
            <p>These Terms govern your use of:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>LayerTao APIs</li>
              <li>Developer dashboard</li>
              <li>Website and related services</li>
            </ul>
            <p>If you do not agree, you must not use the Services.</p>
          </section>

          {/* 2. Use of Services */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              2. Use of Services
            </h2>
            <p>
              You agree to use LayerTao only for lawful purposes and in
              accordance with these Terms.
            </p>
            <p>You must not:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>abuse, overload, or disrupt the Services</li>
              <li>attempt to reverse engineer or exploit the platform</li>
              <li>
                use the Services for illegal, harmful, or abusive activities
              </li>
              <li>bypass rate limits or security mechanisms</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate access for
              violations.
            </p>
          </section>

          {/* 3. API Access */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              3. API Access
            </h2>
            <p>Access to LayerTao APIs requires a valid API key.</p>
            <p>You are responsible for:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>keeping your API keys secure</li>
              <li>all activity associated with your account</li>
            </ul>
            <p className="pt-2">We may:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>enforce rate limits</li>
              <li>modify or deprecate endpoints</li>
              <li>restrict access based on usage patterns</li>
            </ul>
          </section>

          {/* 4. Third-Party Networks */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              4. Third-Party Networks
            </h2>
            <p>
              LayerTao routes requests to third-party decentralized networks.
            </p>
            <p>We do not:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>own or control these networks</li>
              <li>guarantee their availability or performance</li>
            </ul>
            <p className="pt-2">You acknowledge that:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>responses are generated by independent nodes</li>
              <li>output quality may vary</li>
            </ul>
          </section>

          {/* 5. No Guarantees */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              5. No Guarantees
            </h2>
            <p>The Services are provided “as is” and “as available.”</p>
            <p>We do not guarantee:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>uptime or availability</li>
              <li>response accuracy</li>
              <li>performance consistency</li>
            </ul>
            <p>LayerTao is an evolving platform and may change at any time.</p>
          </section>

          {/* 6. Payments */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              6. Payments
            </h2>
            <p>If applicable:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>fees may be charged for API usage</li>
              <li>pricing may change over time</li>
            </ul>
            <p>All payments are non-refundable unless stated otherwise.</p>
          </section>

          {/* 7. Intellectual Property */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              7. Intellectual Property
            </h2>
            <p>LayerTao retains all rights to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>the platform</li>
              <li>APIs</li>
              <li>branding and content</li>
            </ul>
            <p className="pt-2">You retain rights to your input data.</p>
            <p>Outputs generated via the network may be subject to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>third-party model behavior</li>
              <li>unknown ownership conditions</li>
            </ul>
          </section>

          {/* 8. Privacy */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              8. Privacy
            </h2>
            <p>
              Your use of the Services is also governed by our Privacy Policy.
            </p>
          </section>

          {/* 9. Limitation of Liability */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              9. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, LayerTao shall not be
              liable for:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>indirect or consequential damages</li>
              <li>data loss</li>
              <li>service interruptions</li>
              <li>third-party failures</li>
            </ul>
          </section>

          {/* 10. Changes to Terms */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              10. Changes to Terms
            </h2>
            <p>
              We may update these Terms at any time. Continued use of the
              Services constitutes acceptance of the updated Terms.
            </p>
          </section>

          {/* 11. Contact */}
          <section className="space-y-3">
            <h2 className="text-2xl text-white font-medium tracking-tight">
              11. Contact
            </h2>
            <p>
              For questions, contact:{" "}
              <a
                href="mailto:hello@layertao.com"
                className="text-white hover:underline underline-offset-4 transition-colors"
              >
                hello@layertao.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
